### ISSUE TITLE
Schedule call / F2F at Berlin?

### ISSUE THREAD

**Issue by caniszczyk** [cncf/tag-storage#1]
Is the Storage WG interested in an F2F in Berlin?

http://events.linuxfoundation.org/events/cloudnativecon-and-kubecon-europe/extend-the-experience/hackfestandsigs

cc: @cncf/cncf-storage-working-group and @benh

**Comment by hannibalhuang** [comment]
Hi Chris,

I think it is definitely a good idea to have a storage wg session at Berlin

**Comment by stevenphtan** [comment]
I think that's a good idea Chris. I have reserved a table from 2-4pm under Storage WG just in case it gets full.

**Comment by caniszczyk** [comment]
Thanks @stevenphtan !
