### ISSUE TITLE
Schedule first official WG Storage Meeting

### ISSUE THREAD

**Issue by caniszczyk** [cncf/tag-storage#10]
via @benh 

> 
I'd like to try and schedule our first meeting on 4/5, 4/6, or 4/7. Please reply just to me if you have any preferences.

**Comment by caniszczyk** [comment]
doodle poll: http://doodle.com/poll/dpu7qqf9frnv42wm

cc: @cncf/cncf-storage-working-group

**Comment by bgrant0607** [comment]
What is the relationship of this group to https://groups.google.com/forum/#!members/container-storage-interface-working-group ?

**Comment by caniszczyk** [comment]
This is done: https://youtu.be/qAw3y6rdRbs
