### ISSUE TITLE
RFC "Data Storage Concepts"

### ISSUE THREAD

**Issue by caniszczyk** [cncf/tag-storage#2]
https://docs.google.com/document/d/1ntdU4q4ZmfX-EyClxKAK6yaikQleg6maSeijDXi_u0c/edit#heading=h.huattdxrl6ed

**Comment by bassam** [comment]
@caniszczyk looks good. another concept/dimension to add is "[hyper]converged vs [hyper]scaled". I.e. whether compute and storage are scaled together (hyper converged) or scaled independently (hyper scaled).
