### ISSUE TITLE
Update README is goals, etc...

### ISSUE THREAD

**Issue by duglin** [cncf/tag-storage#34]
When a newbie comes to this repo its not clear what the goals/milestones/etc... are.  Can the README be updated with those types of things? Even something as simple as:
- explore/report (whitepaper?) on the landscape of container storage
- get CSI to v1.0
- propose CSI as a CNCF project
...

**Comment by clintkitson** [comment]
Hello @duglin,

The SWG is waiting to hear from the TOC for some of this direction. There has been preliminary work on this topic as addressed in the following PR. For now the SWG is exploring the eco-system of storage related projects.

https://github.com/cncf/wg-storage/pull/33

**Comment by duglin** [comment]
@clintkitson ok that helps - I'll close this issue since that PR should resolve it.
