### ISSUE TITLE
RFC: Container Storage Interface (CSI)

### ISSUE THREAD

**Issue by caniszczyk** [cncf/tag-storage#4]
https://docs.google.com/document/d/1JMNVNP-ZHz8cGlnqckOnpJmHF-DNY7IYP-Di7iuVhQI/edit?usp=sharing

**Comment by caniszczyk** [comment]
cc: @cncf/cncf-storage-working-group for RFC + @cncf/toc if interested

**Comment by bgrant0607** [comment]
cc @thockin @saad-ali

**Comment by thockin** [comment]
Great feedback so far.

**Comment by caniszczyk** [comment]
closing this out now that the CNCF Storage WG is actively meeting:

https://goo.gl/wRqerO & https://youtu.be/qAw3y6rdRbs
