### ISSUE TITLE
Create Logo + branding palette for SIG-Storage

### ISSUE THREAD

**Issue by amye** [cncf/tag-storage#46]
We'd like to have a logo + branding palette for SIG-Storage, this issue is for initial ideas and thoughts.

**Comment by amye** [comment]
Just checking in here, we can get started on this.

**Comment by amye** [comment]
Our designer has come back with some options, attached here. 
[SIG-storage.pdf](https://github.com/cncf/sig-storage/files/3483555/SIG-storage.pdf)

**Comment by chira001** [comment]
In our previous meeting, general consensus was that logos with containers and disks are not ideal as we should not be restricted to containers or transitional volumes.   

There was some discussion about using an animal for the logo (similar to SIG security).  Two ideas are:

A clam (as it stores pearls) - perhaps with eyes and a smiley face to give it some personality
A squirrel (as it stores nuts)

Seeking preferences or any other suggestions! :-)

**Comment by amye** [comment]
So, based on feedback, we now have an entirely new set of logos to review! 
See attached. 
[SIG-storage-v2.pdf](https://github.com/cncf/sig-storage/files/3557329/SIG-storage-v2.pdf)

**Comment by quinton-hoole** [comment]
I think we like the clam concept, but we need to explore alternative images.

There are already many companies with [this](https://seeklogo.com/images/C/clams-clam-logo-99FDEA036F-seeklogo.com.jpg) style of clam as a logo.

Perhaps we could consider the less common perspective, something more in [this](http://getdrawings.com/pearl-icon#pearl-icon-64.png) direction?

**Comment by amye** [comment]
Circling back here, any other thoughts before I have @alexcontini poke at this again?

**Comment by quinton-hoole** [comment]
No new thoughts that I'm aware of.   Let's go for it based on the above

**Comment by amye** [comment]
Here's a slightly different direction, let me know what you're interested in! 
[SIG-storage-v3.pdf](https://github.com/cncf/sig-storage/files/3713580/SIG-storage-v3.pdf)

**Comment by quinton-hoole** [comment]
Personally I like this concept the best:

<img width="411" alt="Screen Shot 2019-10-10 at 09 26 31 " src="https://user-images.githubusercontent.com/43647096/66587900-361fd180-eb40-11e9-9e38-321db340e317.png">

It's simple, obvious, and relatively original.

Let's give it a few days to see what the rest of the SIG thinks.

**Comment by chira001** [comment]
I prefer this one:

![image](https://user-images.githubusercontent.com/7252686/66592985-0c8d9700-eb8e-11e9-8f4e-eb5d802c4256.png)

It is simple as per Quinton's comment, but is more associated with the CNCF logo and makes it less likely to be confused with the K8s SIG Storage.

**Comment by amye** [comment]
Putting on the October 23rd meeting for discussion.

**Comment by chira001** [comment]
![image](https://user-images.githubusercontent.com/7252686/67412486-4790c100-f5b7-11e9-82f6-c9259bfc52c4.png)

I'd vote for number 3.   Please add your vote to the comments :-)

**Comment by xing-yang** [comment]
I vote for 3.

**Comment by sougou** [comment]
Being somewhat design-blind, I have no objections to 3 :)

**Comment by lpabon** [comment]
I vote for 3

**Comment by quinton-hoole** [comment]
I'm fine with 3, 9 or 10.

**Comment by amye** [comment]
Four votes for 3, @chira001. Good to go?

**Comment by chira001** [comment]
> Four votes for 3, @chira001. Good to go?

Yes - good to go with 3 - thank you Amye!

**Comment by alexcontini** [comment]
Great! Here is the final logo - let me know if these work and I will email all the formats!

 
![SIG-storage-logo](https://user-images.githubusercontent.com/27962005/68413218-cbbc7a00-015b-11ea-82f1-99e884624f75.png)

[SIG-storage-logo.pdf](https://github.com/cncf/sig-storage/files/3820976/SIG-storage-logo.pdf)

**Comment by dankohn** [comment]
Please just add to https://github.com/cncf/artwork/blob/master/examples/other.md#sig-security.

**Comment by chira001** [comment]
> Great! Here is the final logo - let me know if these work and I will email all the formats!
> 
> ![SIG-storage-logo](https://user-images.githubusercontent.com/27962005/68413218-cbbc7a00-015b-11ea-82f1-99e884624f75.png)
> 
> [SIG-storage-logo.pdf](https://github.com/cncf/sig-storage/files/3820976/SIG-storage-logo.pdf)

Yes - that is brilliant - thank you!

**Comment by amye** [comment]
Resolved!
